# Generated by Django 3.2.20 on 2023-08-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_userprofile_dietary_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
